### ISSUE TITLE
Cannot controll "TAB" key

### ISSUE THREAD

**Issue by vishalisakar** [nagarsuresh/ngx-mousetrap-angular#1]
while capturing the "Tab" key event preventDefault() method is not working.

```
tabkey = 'tab';

this.subscription = this.service.register(this.tabkey, this.demoArea.nativeElement).subscribe(evt => {
       evt.event.preventDefault()      
    });

```

**Comment by nagarsuresh** [comment]
> while capturing the "Tab" key event preventDefault() method is not working.
> 
> ```
> tabkey = 'tab';
> 
> this.subscription = this.service.register(this.tabkey, this.demoArea.nativeElement).subscribe(evt => {
>        evt.event.preventDefault()      
>     });
> ```

by the time mousetrap gets the tab event is already too late to preventDefault and prevent the focus from going out of the area.
If your requirement is to capture the tab event and not let the focus go out of the area you have two options
1.  Add a separate listener on the div area on keydown and prevent default e.g.
     (this.demoArea.nativeElement as HTMLDivElement).addEventListener('keydown', (event) => event.preventDefault());
2. Second option (better) will be to use a focus trap e.g. Angular CDM a11y module trapFocus directive (cdkTrapFocus)
    https://material.angular.io/cdk/a11y/overview#example
    This can trap the focus on the div area and mousetrap can keep listening to events.
